language: node_js
node_js:
- 8
services:
- mongodb
addons:
  ssh_known_hosts:
  - 162.243.207.143
branches:
  only:
  - master
env:
  global:
  - REMOTE_APP_DIR=/srv/www/node/app/
  - REMOTE_USER=deploy
  - REMOTE_HOST=162.243.207.143
  - SECRET_TOKEN=k399dkkgklsk

before_install:
  - openssl aes-256-cbc -K $encrypted_3471f576b911_key -iv $encrypted_3471f576b911_iv
    -in deploy-key.enc -out deploy-key -d
  - "./scripts/install.sh"
  - yarn global add gulp
  - yarn add -D gulp
before_script:
  - yarn
  - yarn build
after_success:
  - "./scripts/deploy.sh"
